### ISSUE TITLE
没有带后缀Sync的同步方法不止getUpdateManager

### ISSUE THREAD

**Issue by sally2015** [Genuifx/wxa-core#1]
录音管理也是同步方法
`const recorderManager = wx.getRecorderManager()`
以后更新如果有更多不带Sync的每次都要重新安装wxa?

**Comment by Genuifx** [comment]
暴露一个api`wxa.addNoPromise()`这种？

**Comment by sally2015** [comment]
那不是要在文档写明哪些已经被写进你的wxa，还要看不同版本写了哪一些？

**Comment by Genuifx** [comment]
小程序的api也在不断的迭代，除非大家出一个规范，以后按照规范来做升级（有点天真:smile:），否则没有一劳永逸的方法。
